/* Generated By:JavaCC: Do not edit this line. DecimalGrammarConstants.java */
package lab5;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DecimalGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int POINT = 8;
  /** RegularExpression Id. */
  int ZERO_CASE = 9;
  /** RegularExpression Id. */
  int DEFAULT_CASE = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"-\"",
    "\"+\"",
    "<DIGIT>",
    "\".\"",
    "<ZERO_CASE>",
    "<DEFAULT_CASE>",
    "\";\"",
  };

}
