/* Generated By:JavaCC: Do not edit this line. question7Constants.java */
package question7;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface question7Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 9;
  /** RegularExpression Id. */
  int CLOSED_PARENTHESIS = 10;
  /** RegularExpression Id. */
  int OPEN_BRACE = 11;
  /** RegularExpression Id. */
  int CLOSED_BRACE = 12;
  /** RegularExpression Id. */
  int EQUALS = 13;
  /** RegularExpression Id. */
  int COMPARISON = 14;
  /** RegularExpression Id. */
  int LESS = 15;
  /** RegularExpression Id. */
  int GREATER = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LETTER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "<COMPARISON>",
    "\"<\"",
    "\">\"",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\"while\"",
  };

}
