/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package lab4;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int CAPITAL = 7;
  /** RegularExpression Id. */
  int LOWERCASE = 8;
  /** RegularExpression Id. */
  int DOB = 9;
  /** RegularExpression Id. */
  int XNUMBER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/\"",
    "<DIGIT>",
    "<CAPITAL>",
    "<LOWERCASE>",
    "<DOB>",
    "<XNUMBER>",
    "\"_\"",
    "\";\"",
  };

}
