/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package lab4;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int UPPERCASE = 10;
  /** RegularExpression Id. */
  int UCASE = 11;
  /** RegularExpression Id. */
  int LOWERCASE = 12;
  /** RegularExpression Id. */
  int LCASE = 13;
  /** RegularExpression Id. */
  int CONSTANT = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "<UPPERCASE>",
    "<UCASE>",
    "<LOWERCASE>",
    "<LCASE>",
    "<CONSTANT>",
    "<DIGIT>",
    "\";\"",
  };

}
